[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib"]
test = "test"
script = "contracts/script"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true

[rpc_endpoints]
rise = "https://testnet.riselabs.xyz"
local = "http://localhost:8545"

[etherscan]
rise = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.testnet.riselabs.xyz/api" }