name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  FOUNDRY_PROFILE: ci

jobs:
  contracts:
    name: Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run forge build
        run: forge build --sizes
        working-directory: ./

      - name: Run forge tests
        run: forge test -vvv
        working-directory: ./

      - name: Run forge coverage
        run: forge coverage
        working-directory: ./
        
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
        
      - name: Run tests
        run: npm test -- --passWithNoTests
        working-directory: ./frontend

  backend-ai:
    name: AI Risk Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/ai-risk-engine/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend/ai-risk-engine
      
      - name: Build
        run: npm run build
        working-directory: ./backend/ai-risk-engine
      
      - name: Run tests
        run: npm test -- --passWithNoTests
        working-directory: ./backend/ai-risk-engine
        
  backend-keeper:
    name: Keeper Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/keeper/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend/keeper
      
      - name: Build
        run: npm run build
        working-directory: ./backend/keeper
      
      - name: Run tests
        run: npm test -- --passWithNoTests
        working-directory: ./backend/keeper